### PR TITLE
Make buffer_length dynamic

### PR DESCRIPTION
**Pull request by longemen3000**
this allows resizing the buffer on the REPL. it is needed, for calling `get_fluid_param_string("Water,"JSON")` without erroring.

### CODE REVIEW

**Comment by barche** [comment]
Actually, I don't understand why `buffer_length` and `message_buffer` need to be globals, this would cause trouble if this is used from multiple threads.

**Comment by ibell** [comment]
I'm not a julia person, but I guess this is to improve the speed by
avoiding reallocation of resources

**Comment by longemen3000** [comment]
i did a check on all fluids currently present on CoolProp, and the longest is Ammonia with a required buffer length of 30916.

**Comment by barche** [comment]
I made a copy at PR #34 since I failed to modify this one, some of the calls to `length` needed to be replaced with `Base.length` because `length` was also in the function argument list and took precedence.

**Pull request closed without merging**
