### PR TITLE
Use JLL for binaries

### PR DESCRIPTION
**Pull request by barche**
I noticed the build script in master fails, because the library on sourceforge is no longer at the specified address. This PR addresses this by switching to the "modern" Julia style of using a JLL package ( see https://julialang.org/blog/2019/11/artifacts/ ) for binary dependencies.

The build script for the binaries is at: https://github.com/JuliaPackaging/Yggdrasil/blob/master/C/CoolProp/build_tarballs.jl

I also fixed the tests, which required adapting the `fails_critical_point` and `fails_tcrit_eq_treducing` lists, you may want to check if that is OK since I don't really know what I'm doing there ;)

Note that with this PR, the package can only be used with **Julia 1.3 and newer** because of the use of the JLL.

### CODE REVIEW

**Comment by ibell** [comment]
Can you please find another Julia person to test these changes on another platform or two to make sure?  I'm not a Julia user and I don't want to break things by merging questionable code.

**Comment by barche** [comment]
I have added github workflow tests, I think it needs to be enabled on this repository for the tests to run here, but you can see the results here: https://github.com/barche/CoolProp.jl/actions/runs/445489526

So it works on Windows, Mac and linux!

**Comment by ibell** [comment]
Can you please lay out in detail what steps are required to get the github
actions to fire on CoolProp/CoolProp.jl?

**Comment by ibell** [comment]
Thanks for the info, I'll merge this and enable the actions.

**Pull request merged**
